baseurl = "https://ringotc.github.io/"
languageCode = "zh-cn"
title = "RingoTC's Blog"
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/RingoTC\">Han Liao</a> 1998"
disqusShortname = ""
googleAnalytics = ""

[params]

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "https://github.com/RingoTC"
  fa_icon = "fab fa-github"


[[params.social]]
  url = "https://twitter.com/tcringo"
  fa_icon = "fab fa-twitter"

  [[params.social]]
  url = "https://weibo.com/u/3922864097"
  fa_icon = "fab fa-weibo"